config/routes.rb
SimpleHotel::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "statistics/all"

  resources :monthly_costs


  match "rooms/list_rooms" => 'rooms#list_rooms', as: :listrooms
  match "rooms/manage_room/:id" => "rooms#manage_room", as: :manageroom
  match "checkins/checkout/(:id)" => "checkins#checkout", as: :checkout
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match "dashboard/index/(:date)" => "dashboard#index", as: :dashboard
  
  resources :customers do
    match :customer_id_return, :on => :collection
  end
  resources :costs
  resources :rooms do
  	match :rate, :on => :collection
  end
  resources :room_types do
    match :available_rooms, :on => :collection
  end
	

  resources :checkins do
    get :customer_autocomplete, :on => :collection
    get :totalcost, :on => :collection
   
  end
  
  resources :line_items
  resources :invoices
  resources :monthly_costs
  devise_for :users, :skip => :registrations

    
  root :to => 'dashboard#index'
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :checkin
	has_one :customer, :through => :checkin
	has_one :room, :through => :checkin
	has_many :line_items, :through => :checkin
	
	after_create :set_checkin_true
	
  attr_accessible :checkin_id, :rate, :paid_method, :checkin_reference, :customer_name, :room_name
  attr_accessor :customer_name, :room_name
  
  def customer_name=(name)
		customer= Customer.find_by_name(name)
		if customer
			self.customer_id = customer.id
		else
			errors[:customer_name] << "Invalid name entered"
		end
	end

	def customer_name
  	#Customer.find(self.checkin.customer_id).name if self.checkin.customer_id
	  self.checkin.customer.name
	end
	
	def room_name
	  self.checkin.room.name
	end
	
	def self.total_cost(costs)
        
    total = 0
    costs.each do |cost|
      total += cost.checkin.clean_income
    end
    total
  end
  
  def set_checkin_true
    self.checkin.update_attribute(:paid, true)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  
  def index
    @q = Invoice.joins(:checkin).order("checkins.room_id asc").search(params[:q])
    @pdf_res = @q.result
    @invoices = @q.result.paginate(:page => params[:page], :per_page => 10)		
		@sum = Invoice.total_cost(@q.result)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
      format.pdf { render pdf: @pdf_res }
    end
  end
  
  def create
    @invoice = Invoice.new(params[:invoice])
    
    respond_to do |format|
      if @invoice.save
        @invoice.checkin.checkout
        format.html { redirect_to @invoice, notice: 'invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @invoice = Invoice.find(params[:id])
    
    respond_to do |format|
      format.html #html view
      format.pdf  { render :layout => true  }
		end
  end
end

app/helpers/invoices_helper.rb
# encoding: UTF-8
module InvoicesHelper
  def paid_method_string(invoice)
    html = ''
    if invoice.paid_method == 1
      html = "Μετρητά"
    elsif invoice.paid_method == 2
      html = "Κάρτα"
    else
      html = ''
    end
  end
  
  def rate_info(invoice)
    html="<table>"
    html+="<tr><td class=\"imp\">Σύνολο</td><td class=\"imp\">#{invoice.checkin.clean_income}</td></tr>"
    html+="<tr><td class=\"imp\">Κόστος δωματίου</td><td>#{(invoice.checkin.todate - invoice.checkin.fromdate).to_i} x #{invoice.checkin.rate}</td></tr>"
    html+="<tr><td class=\"imp\">Έκπτωση</td><td>#{invoice.checkin.room_discount}</td></tr>"
    html+="<tr><td class=\"imp\">Extra</td><td>#{invoice.checkin.room_costs}</td></tr>"
    html+="</table>"
    html.html_safe
  end
end

app/views/invoices/create.html.erb
<h1>Invoices#create</h1>
<p>Find me in app/views/invoices/create.html.erb</p>

app/views/invoices/index.html.erb
<%- model_class = Invoice -%>
<div class="page-header">
  <h1>Λογιστήριο</h1>
</div>

<%= search_form_for @q, :html => { class: 'well' } do |f| %>

<table class="table table-striped">
  <thead>
    <tr>
		<th><%= sort_link @q, :room_name, model_class.human_attribute_name(:room_name) %></th>
      <th><%= sort_link @q, :customer_name, model_class.human_attribute_name(:customer_name) %></th>
      <th>Σύνολο</th>
       <th><%= sort_link @q, :created_at, model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
		  <td><%= invoice.room_name %></td>
        <td><%= link_to invoice.customer_name, invoice_path(invoice.id) %></td>
        <td>
        		<%= rate_info(invoice) %>
        </td>
        <td><%= invoice.created_at %></td>
        <td>
          <%= link_to "Στοιχεία",
                      invoice_path(invoice), :class => 'btn btn-mini' %>
         
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<% end %>


<%= will_paginate @invoices %>

<%= link_to 'Εκτύπωση', current_url(format:'pdf'), target: '_blank', class:'btn btn-danger' %>

<%= content_for :sidebar do %>
	<%= search_form_for @q, :html => { class: 'well' } do |f| %>	
	  <div class="control-group">
	    <label class="control-label" for="q_created_at_lteq">Πελάτης</label> 
	    <div class="controls">
	      <%= f.text_field :customer_name_cont %>
	    </div>
	  	</div>
		
		<div class="control-group">
		<label class="control-label">Τρόπος Πληρωμής</label> 
	    <div class="controls">
	      <%= f.select :paid_method_eq, options_for_select([['Μετρητά', 1], ['Κάρτα', 2]]) %>
	    </div>
	  	</div>
	
		<div class="control-group">
		    <label class="control-label" for="q_created_at_lteq">Δωμάτιο</label>
		    <div class="controls">
		      <%= f.text_field :room_name_cont %>
		    </div>
		  </div>
	  
		<div class="control-group">
		    <label class="control-label" for="q_created_at_lteq">Από</label>
		    <div class="controls">
		      <%= f.text_field :created_at_gteq %>
		    </div>
		</div>

		<div class="control-group">
		    <label class="control-label" for="q_created_at_lteq">Έως</label>
		    <div class="controls">
		      <%= f.text_field :created_at_lteq %>
		    </div>
		</div>

	  <div class="form-actions">
	    <%= f.submit class: 'btn btn-primary' %>
	    <%= link_to "Clear", invoices_path, class: "btn" %>
	  </div>
	<%end%>
	
	<div class="well">
		<h5>Σύνολο</h5>
		<%= @sum %>
	</div>
	
<%end%>

app/views/invoices/show.html.erb
<div class="page-header">
  <h3>Απόδειξη <%= @invoice.checkin.reference%> <%= @invoice.checkin.fromdate %> - <%= @invoice.checkin.todate %></h3> 
</div>
<table class="table table-striped">
	<tbody>
		<tr>
			<th>Κόστος Δωματίου</th>
			<td><%= @invoice.checkin.room_rate %></td>
		</tr>
		<tr>
			<th>Εγγύηση:</th>
			<td><%= @invoice.checkin.deposit %></td>
		</tr>
		<tr>	
			<th>Προπληρωμή:</th>
			<td><%= @invoice.checkin.prepaid %></td>
		</tr>
		<tr>	
			<th>Έκπτωση:</th>
			<td><%= @invoice.checkin.room_discount %></td>
		</tr>  
		<tr>
			<td colspan=2>  <h5>Έξοδα</h5></td>
		</tr>
   	<% @invoice.checkin.line_items.each do |item|%>
  		<tr>
        <td><%= item.created_at %>-<%= item.cost.name %></td>
        <td><%= item.rate %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<h5>Σύνολο: <%= @invoice.rate %> </h5>
<h5>Τρόπος πληρωμής: <%= paid_method_string(@invoice) %></h5>

<%= link_to 'Εκτύπωση', invoice_path(@invoice, format:'pdf'), target: '_blank', class:'btn btn-danger' %>