config/routes.rb
SimpleHotel::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "statistics/all"

  resources :monthly_costs


  match "rooms/list_rooms" => 'rooms#list_rooms', as: :listrooms
  match "rooms/manage_room/:id" => "rooms#manage_room", as: :manageroom
  match "checkins/checkout/(:id)" => "checkins#checkout", as: :checkout
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match "dashboard/index/(:date)" => "dashboard#index", as: :dashboard
  
  resources :customers do
    match :customer_id_return, :on => :collection
  end
  resources :costs
  resources :rooms do
  	match :rate, :on => :collection
  end
  resources :room_types do
    match :available_rooms, :on => :collection
  end
	

  resources :checkins do
    get :customer_autocomplete, :on => :collection
    get :totalcost, :on => :collection
   
  end
  
  resources :line_items
  resources :invoices
  resources :monthly_costs
  devise_for :users, :skip => :registrations

    
  root :to => 'dashboard#index'
end

app/models/cost.rb
# encoding: UTF-8
class Cost < ActiveRecord::Base
  has_many :line_items
  has_many :checkins, :through => :line_items
  has_many :monthly_costs
  
  validates :name, :cost_type, presence: true 
  
  attr_accessible :description, :name, :cost_type, :cost_type_name
  attr_accessor :cost_type_name
  
  def cost_type_name
    if self.cost_type == 1
      return "Ειδικό"
    elsif self.cost_type == 2
      return "Γενικό"
    end
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @costs }
    end
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    @cost = Cost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/new
  # GET /costs/new.json
  def new
    @cost = Cost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/1/edit
  def edit
    @cost = Cost.find(params[:id])
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(params[:cost])

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render json: @cost, status: :created, location: @cost }
      else
        format.html { render action: "new" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /costs/1
  # PUT /costs/1.json
  def update
    @cost = Cost.find(params[:id])

    respond_to do |format|
      if @cost.update_attributes(params[:cost])
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost = Cost.find(params[:id])
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= simple_form_for @cost, html: { class:"form-horizontal"} do |f| %>
	<%= f.input :name %>
	<%= f.input :description, as: :text %>
	<%= f.input :cost_type, collection: { "Ειδικό" => 1, "Γενικό" => 2} %>
	
	<div class="form-actions">
		<%= f.submit nil, :class => 'btn btn-primary' %>
	   <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	               costs_path, :class => 'btn' %>
	</div>
<% end %>

app/views/costs/edit.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/costs/index.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
 		<th><%= model_class.human_attribute_name(:cost_type) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= link_to cost.name, cost_path(cost) %></td>
        <td><%= cost.description %></td>
		  <td><%= cost.cost_type_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cost_path(cost), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cost_path(cost),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cost_path,
            :class => 'btn btn-primary' %>

app/views/costs/new.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/costs/show.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @cost.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @cost.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              costs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cost_path(@cost), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cost_path(@cost),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>