config/routes.rb
SimpleHotel::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "statistics/all"

  resources :monthly_costs


  match "rooms/list_rooms" => 'rooms#list_rooms', as: :listrooms
  match "rooms/manage_room/:id" => "rooms#manage_room", as: :manageroom
  match "checkins/checkout/(:id)" => "checkins#checkout", as: :checkout
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match "dashboard/index/(:date)" => "dashboard#index", as: :dashboard
  
  resources :customers do
    match :customer_id_return, :on => :collection
  end
  resources :costs
  resources :rooms do
  	match :rate, :on => :collection
  end
  resources :room_types do
    match :available_rooms, :on => :collection
  end
	

  resources :checkins do
    get :customer_autocomplete, :on => :collection
    get :totalcost, :on => :collection
   
  end
  
  resources :line_items
  resources :invoices
  resources :monthly_costs
  devise_for :users, :skip => :registrations

    
  root :to => 'dashboard#index'
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :checkin
  belongs_to :cost
  has_one :invoice, :through => :checkin
  
  attr_accessible :rate, :checkin_id, :cost_id
  
  validates :rate, :cost_id, :checkin_id, presence: true
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  
  def create
    @line_item = LineItem.new(params[:line_item])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'line_item was successfully created.' }
        format.js 
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end
  
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to(@line_item) }
      format.js   { render :nothing => true }
  	end
  end

end

app/views/line_items/_form.html.erb
<%= simple_form_for( @line_item, remote: true, html: { class: "form-horizontal"} ) do |f| %>
	<%=f.association :cost, collection: Cost.where('cost_type = ?', 1).order('name') %>
	<%=f.input :rate, input_html: { class: "input-mini" } %>
	<%=f.input :checkin_id, as: :hidden%>
	<%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>

app/views/line_items/create.js.erb
$('#LineItemsList table tbody').append("<tr><td><%= escape_javascript(@line_item.cost.name) %></td><td><%= escape_javascript(@line_item.rate.to_s) %></td><td><%= escape_javascript(link_to 'Διαγραφή', line_item_path(@line_item), :method => :delete, :remote => true , :rel => "nofollow",:data => { :confirm => t('.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger delete-cost') %></td></tr>")