config/routes.rb
SimpleHotel::Application.routes.draw do
  
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "statistics/all"

  resources :monthly_costs


  match "rooms/list_rooms" => 'rooms#list_rooms', as: :listrooms
  match "rooms/manage_room/:id" => "rooms#manage_room", as: :manageroom
  match "checkins/checkout/(:id)" => "checkins#checkout", as: :checkout
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match "dashboard/index/(:date)" => "dashboard#index", as: :dashboard
  
  resources :customers do
    match :customer_id_return, :on => :collection
  end
  resources :costs
  resources :rooms do
  	match :rate, :on => :collection
  end
  resources :room_types do
    match :available_rooms, :on => :collection
  end
	

  resources :checkins do
    get :customer_autocomplete, :on => :collection
    get :totalcost, :on => :collection
   
  end
  
  resources :line_items
  resources :invoices
  resources :monthly_costs
  devise_for :users, :skip => :registrations

    
  root :to => 'dashboard#index'
end

app/models/checkin.rb
# encoding: UTF-8
class Checkin < ActiveRecord::Base
  belongs_to :room
  belongs_to :customer
  
  has_many :line_items
  has_many :costs, :through => :line_items
  
  has_one :invoice
  
  after_create :save_reference
  after_update :set_room_inactive
  before_destroy :open_room
  
  
  attr_accessible :customer_id, :deposit, :description, :discount, :fromdate, :prepaid, :rate, :reference, :room_id, 
 	:todate, :customer_name, :room_type, :paid
	
	attr_accessor :customer_name, :room_type
	
	validates :customer_id, :rate, :room_id, :fromdate, :todate, presence: true

	validates_numericality_of :rate, :prepaid, :discount, :deposit
	validate :date_validation
	
	has_event_calendar :start_at_field  => 'fromdate', :end_at_field => 'todate'
	
	
	def date_validation
    if self.todate < self.fromdate
      errors.add(:todate, "Ημερομηνία")
      return false
    else
      return true
    end
  end
  
  def checkout
    self.update_attribute(:checked_out, true)
    self.room.update_attribute(:status, false)
  end
		
	def customer_name=(name)
		customer= Customer.find_by_name(name)
		if customer
			self.customer_id = customer.id
		else
			errors[:customer_name] << "Invalid name entered"
		end
	end

	def customer_name
  	Customer.find(customer_id).name if customer_id
	end
  
  def room_type
    room_type = Room.find(room_id).room_type_id if room_id
    RoomType.find(room_type).id if room_id 
  end
  
  
  def room_name
    Room.find(room_id).name if room_id
  end
  
  # Οικονομικά
  def room_rate
    days = (self.todate - self.fromdate).to_i + 1
    
    total = days * self.rate
  end
  
  def room_discount
    days = (self.todate - self.fromdate).to_i + 1
    
    total = days * self.discount
  end
  
  def room_costs
    costs = self.line_items
    final_cost = 0
    costs.each do |li| 
      final_cost += li.rate
    end
    return final_cost
  end
  
  def total_cost
    self.room_rate - (self.room_discount + self.prepaid + self.deposit) + self.room_costs
  end
  
  def clean_income
      self.room_rate - self.room_discount  + self.room_costs
  end
  
  def save_reference
    self.update_attribute(:reference, self.id.to_s + "-" + self.customer_name)
    self.update_attribute(:checked_out, false)
    self.room.update_attribute(:status, true)
  end
  
  def open_room
    self.room.update_attribute(:status, false)
  end
  
  def set_room_inactive
    if (self.room.status == false)
      self.room.update_attribute(:status, true)
    end
  end
  
  def cost_per_day
    
  end
    
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @q = Checkin.search(params[:q])
    @checkins = @q.result.where(" checked_out = ? ", false).paginate(:page => params[:page], :per_page => 10)		
		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkins }
    end
  end

  def new
    @checkin = Checkin.new
    @customer = Customer.new
		@room_types = RoomType.all
				
		if params[:room_id].present?
		  @checkin.room_id = params[:room_id]
		  @checkin.rate = params[:rate]
		  @rooms = RoomType.find(@checkin.room.room_type).rooms.where("status = ?", false)
		else
		  @rooms = Room.where("status = ?", false)
		end
		@checkin.prepaid = @checkin.deposit = @checkin.discount = 0
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkins }
    end
  end
  
  def show
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkin }
    end
  end
  
  def create
    @checkin = Checkin.new(params[:checkin])
    @customer = Customer.new()
    @room_types = RoomType.all
		@rooms = Room.all
            
    respond_to do |format|
      if @checkin.save
        format.html { redirect_to listrooms_path, notice: 'checkin was successfully created.' }
        format.json { render json: @checkin, status: :created, location: @checkin }
      else
        format.html { render action: "new" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @checkin = Checkin.find(params[:id])
     
    respond_to do |format|
      if (@checkin.room_id != params[:checkin][:room_id])
           @checkin.open_room
      end
      if @checkin.update_attributes(params[:checkin])
        format.html { redirect_to checkins_path, notice: 'Checkin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /checkins/1/edit
  def edit
    @checkin = Checkin.find(params[:id])
    @room_types = RoomType.all
    @rooms = Room.where("room_type_id = ?", @checkin.room_type)
    @customer = Customer.new
  end
  
  def destroy
    @checkin = Checkin.find(params[:id])
    @checkin.destroy

    respond_to do |format|
      format.html { redirect_to checkins_url }
      format.json { head :no_content }
    end
  end
  
  #Autocomplete
  def customer_autocomplete
    if params[:term]
      like= "%".concat(params[:term].concat("%"))
      customers = Customer.where("name like ?", like)
    else
      customers = Customer.all
    end
    list = customers.map {|u| Hash[ id: u.id, label: u.name, name: u.name]}
   
    render json: list
  end
  #Ajax update costs
  def totalcost
    if !params[:checkin_id].blank?
      checkin = Checkin.find(params[:checkin_id])
    end
    
    render :json => { total_cost: checkin.total_cost, room_costs: checkin.room_costs }
  end
  
  def customer_name=(name)
		customer= Customer.find_by_name(name)
		if customer
			self.customer_id = customer.id
		else
			errors[:customer_name] << "Invalid name entered"
		end
	end

	def customer_name
  	Customer.find(customer_id).name if customer_id
	end
	
	# Checking out
	def checkout
	  @checkin = Checkin.find(params[:id])
		@invoice = Invoice.new({checkin_id:@checkin.id, rate:@checkin.total_cost})
		
		respond_to do |format|
      format.html 
      format.json 
    end
  end
  	
end

app/views/checkins/_form.html.erb
<%= simple_form_for(@checkin, html:{ class:'form-horizontal' }) do |f| %>
	<%= f.input :customer_name %><a href="#new_customer" role="button" class="btn btn-primary" data-toggle="modal">Νέος πελάτης</a>
	<%= f.input :room_type, collection: @room_types %>
	<%= f.input :room_id, collection: @rooms %>
   <%= f.input :customer_id, as: :hidden %>
	<%= f.input :fromdate, as: :string, input_html: { :value => @checkin.fromdate.to_s  }%>
	<%= f.input :todate, as: :string, input_html: { :value => @checkin.todate.to_s  }%>
	<%= f.input :rate, input_html: { class:"input-mini" } %>
	<%= f.input :deposit, input_html: { class:"input-mini" } %>
	<%= f.input :prepaid, input_html: { class:"input-mini" } %>
	<%= f.input :discount, input_html: { class:"input-mini" } %>
	<%= f.input :description %>
	<div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                checkins_path, :class => 'btn' %>
  </div>
<% end %>

<!-- Modal -->
<div id="new_customer" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Νέος πελάτης</h3>
	</div>
		<div class="modal-body">
		</div>
<%= render :partial => "customers/ajaxform", :object => @customer %>
</div>

app/views/checkins/_info.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><span id="CheckinId"><%= @checkin.id %></span></span>-<%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer_name) %>:</strong></dt>
  <dd><%= @checkin.customer_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_name) %>:</strong></dt>
  <dd><%= @checkin.room_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rate) %>:</strong></dt>
  <dd><%= @checkin.rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deposit) %>:</strong></dt>
  <dd><%= @checkin.deposit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prepaid) %>:</strong></dt>
  <dd><%= @checkin.prepaid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @checkin.discount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fromdate) %>:</strong></dt>
  <dd><%= @checkin.fromdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:todate) %>:</strong></dt>
  <dd><%= @checkin.todate %></dd>
</dl>

<div class="form-actions">
 
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_checkin_path(@checkin), :class => 'btn btn-primary' %>
</div>

app/views/checkins/checkout.html.erb
<div class="well">
	<h3><%= @checkin.reference %>, room <%= link_to @checkin.room.name, manageroom_path(id: @checkin.room.id) %>, <%= @checkin.customer.email %></h3>
	
	<hr>
	<h5>Αναλυτικά</h5>
	<table class="table table-striped">
   <tbody>
   	<tr>
   		<th> <%= @checkin.fromdate %> - <%= @checkin.todate %></th>
   		<td><%= @checkin.room_rate %></td>
   	</tr>
   	<tr>
   		<th>Προπληρωμένο</th>
   		<td><%= @checkin.prepaid %></td>
   	</tr>
   	<tr>
   		<th>Εγγύηση</th>
   		<td><%= @checkin.deposit %></td>
   	</tr>
   	<tr>
   		<th>Έκπτωση</th>
   		<td><%= @checkin.room_discount %></td>
   	</tr>
		<tr>
			<td colspan=2>  <h5>Έξοδα</h5></td>
		</tr>
   	<% @checkin.line_items.each do |item|%>
  <tr>
        <td><%= item.created_at %>-<%= item.cost.name %></td>
        <td><%= item.rate %></td>
        
      </tr>
	<% end %>
	   </tbody>
  </table>
  <hr>
  <h5>Σύνολο: <%= @checkin.total_cost%> </h5>
  <%=simple_form_for(@invoice, html:{ class:'form-horizontal' }) do |f|%>
  	<%= f.input :rate, input_html: {class:"input-mini"} %>
	<%= f.input :paid_method, collection:{"Μετρητά" => 1, "Κάρτα" => 2}, include_blank: false, :class => 'text_area' %>
	<%= f.input :checkin_id, as: :hidden %>
	<%= f.submit :checkout, class:"btn btn-danger" %>
  <% end %>
</div>

app/views/checkins/edit.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/checkins/index.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= search_form_for @q, :html => { class: 'well' } do |f| %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:reference) %></th>
      <th><%= sort_link @q, :customer_name, model_class.human_attribute_name(:customer_name) %></th>
      <th><%= sort_link @q, :room_name, model_class.human_attribute_name(:room_name) %></th>
      <th><%= model_class.human_attribute_name(:fromdate) %></th>
      <th><%= model_class.human_attribute_name(:todate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= link_to checkin.reference, checkin_path(checkin) %></td>
        <td><%= link_to checkin.customer_name, customer_path(checkin.customer_id) %></td>
        <td><%= link_to checkin.room_name, room_path(checkin.room_id) %></td>
        <td><%= checkin.fromdate %></td>
        <td><%= checkin.todate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_checkin_path(checkin), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("delete")),
                      checkin_path(checkin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<% end %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_checkin_path,
            :class => 'btn btn-primary' %>

<%= will_paginate @checkins %>

<%= content_for :sidebar do %>
	<%= search_form_for @q, :html => { class: 'well' } do |f| %>	
	  <div class="control-group">
	    <%= f.label :customer_name_cont, class: 'control-label' %> 
	    <div class="controls">
	      <%= f.text_field :customer_name_cont %>
	    </div>
	  </div>

	  <div class="control-group">
	    <%= f.label :room_name_cont, class: 'control-label' %> 
	    <div class="controls">
	      <%= f.text_field :room_name_cont %>
	    </div>
	  </div>

		<div class="control-group">
		    <%= f.label :created_at_gt, class: 'control-label' %> 
		    <div class="controls">
		      <%= f.text_field :created_at_gt %>
		    </div>
		</div>

		<div class="control-group">
		    <%= f.label :created_at_lt, class: 'control-label' %> 
		    <div class="controls">
		      <%= f.text_field :created_at_lt %>
		    </div>
		</div>

	  <div class="form-actions">
	    <%= f.submit class: 'btn btn-primary' %>
	    <%= link_to "Clear", checkins_path, class: "btn" %>
	  </div>
	<%end%>
<%end%>

app/views/checkins/new.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/checkins/show.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer_name) %>:</strong></dt>
  <dd><%= @checkin.customer_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_name) %>:</strong></dt>
  <dd><%= @checkin.room_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rate) %>:</strong></dt>
  <dd><%= @checkin.rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deposit) %>:</strong></dt>
  <dd><%= @checkin.deposit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prepaid) %>:</strong></dt>
  <dd><%= @checkin.prepaid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @checkin.discount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fromdate) %>:</strong></dt>
  <dd><%= @checkin.fromdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:todate) %>:</strong></dt>
  <dd><%= @checkin.todate %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              checkins_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_checkin_path(@checkin), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("Checkout")),
              checkin_path(@checkin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>